export const GRID_SIZE = 0.5
export const GRID_WIDTH = Math.ceil(30 / GRID_SIZE)
export const GRID_HEIGHT = Math.ceil(30 / GRID_SIZE)
export const DRAG_THRESHOLD = 5
export const CLICK_TIMEOUT = 200

export const PLAYER_CONFIG = {
  HEIGHT: 1.7,
  RADIUS: 0.3,
  SAFETY_BUFFER: 0.3,
  MOVEMENT_SPEED: 5,
  MOVEMENT_ACCELERATION_DURATION: 0.8,
  ROTATION_SPEED: (120 / 180) * Math.PI,
  ROTATION_ACCELERATION_DURATION: 0.5,
}

export const ARTWORK_CONFIG = {
  WIDTH: 2,
  HEIGHT: 2,
  COLOR: 0xff0000,
  WALL_OFFSET: 0.152,
  VERTICAL_POSITION: 2,
}
